### ISSUE TITLE
Run testsuite against under development perftools

### ISSUE THREAD

**Issue by mhiramat** [rfmvh/perftool-testsuite#1]
Currently the perftools testsuite depends on PATH env to find perf command.
However, most possible use case of tests is developing phase, like adding new feature or fixing some bugs. In that case, we usually don't install until it can pass the tests.
Thus, the testsuites must run against pre-installed binaries.

So, please add an option to pass PERF_PATH or something like that to make file or run_all command so that user can give the development kernel tree, e.g.

`# make PERF_PATH=$HOME/linux/tools/perf/ check`

**Comment by rfmvh** [comment]
There already is a variable for that in `common/settings.sh`, called `CMD_PERF`. The `perf` available in `PATH` is only a default value, if you set this environment variable manually, you can override it. Similarly, the other `CMD_*` variables are possible to modify, so you may easily change the load `perf` is running against.

There are two files: `settings.sh` and `parametrization.sh`, while `parametrization.sh` aims rather on selecting testcases to be run (the testsuite might serve as a smoke test or as a more thorough one) and `settings.sh` controls the rest.

Is it suitable to you like this?

**Comment by mhiramat** [comment]
Thanks, I see that the settings.sh is a kind of configuration file. I'll try to use it.
Actually, I also tried to use PATH, but since I ran testsuite by sudo, it changes PATH to safer one... CMD_PERF looks good to me.

Thanks again!
